language: java

matrix:
  include:
    - os: linux
      dist: trusty
      jdk:
        - openjdk8
    - os: osx
      osx_image: xcode9.3
      jdk:
        - oraclejdk8

cache:
  directories:
    - $HOME/.m2